package ttr.utgaave.nordic;

import ttr.data.Destination;
import ttr.data.Colour;
import ttr.oppdrag.Mission;
import ttr.rute.Route;
import ttr.utgaave.GameVersion;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;


public final class Nordic extends GameVersion {
	public static final String tittel = "Nordic countries";
	private static final String bilde = "nordic_map.jpg";
	
	public Nordic() {
		super(tittel,bilde);
	}

	protected Set<Route> leggTilRuter() {
		routes = new HashSet<>();
		int ruteid = 0;
		routes.add(new Route (ruteid,Destination.Oslo,Destination.Ørebro,2,Colour.gul,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Oslo,Destination.Ørebro,2,Colour.grønn,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Ørebro,Destination.Stockholm,2,Colour.lilla,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Ørebro,Destination.Stockholm,2,Colour.svart,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Stockholm,Destination.Norrkøping,1,Colour.oransje,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Stockholm,Destination.Norrkøping,1,Colour.raud,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Stockholm,Destination.Sundsvall,4,Colour.valfri,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Stockholm,Destination.Sundsvall,4,Colour.valfri,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Sundsvall,Destination.Østersund,2,Colour.grønn,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Østersund,Destination.Trondheim,2,Colour.svart,false,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Trondheim,Destination.MoIRana,5,Colour.grønn,true,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Trondheim,Destination.MoIRana,6,Colour.raud,false,2));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Trondheim,Destination.Åndalsnes,2,Colour.kvit,false,1));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Åndalsnes,Destination.Bergen,5,Colour.svart,false,2));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Lillehammer,Destination.Trondheim,3,Colour.oransje,true,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Lillehammer,Destination.Oslo,2,Colour.lilla,true,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Lillehammer,Destination.Åndalsnes,2,Colour.gul,true,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Oslo,Destination.Bergen,4,Colour.raud,true,0));
		ruteid++;
		routes.add(new Route (ruteid,Destination.Oslo,Destination.Bergen,4,Colour.blå,true,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Stavanger,Destination.Bergen,2,Colour.lilla,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Stavanger,Destination.Kristiansand,2,Colour.grønn,true,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Stavanger,Destination.Kristiansand,3,Colour.oransje,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Kristiansand,Destination.Aalborg,2,Colour.raud,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Kristiansand,Destination.Oslo,2,Colour.svart,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Oslo,Destination.Aalborg,3,Colour.kvit,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Aalborg,Destination.Århus,1,Colour.lilla,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Aalborg,Destination.Gøteborg,1,Colour.valfri,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Århus,Destination.København,1,Colour.valfri,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.København,Destination.Gøteborg,2,Colour.svart,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Oslo,Destination.Gøteborg,2,Colour.oransje,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.København,Destination.Karlskrona,2,Colour.grønn,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.København,Destination.Karlskrona,2,Colour.blå,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Norrkøping,Destination.Karlskrona,3,Colour.kvit,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Norrkøping,Destination.Karlskrona,3,Colour.gul,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Gøteborg,Destination.Norrkøping,3,Colour.valfri,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Gøteborg,Destination.Ørebro,2,Colour.blå,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Norrkøping,Destination.Ørebro,2,Colour.valfri,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Stockholm,Destination.Tallinn,4,Colour.grønn,false,2));
		ruteid++; routes.add(new Route (ruteid,Destination.Tallinn,Destination.Helsinki,2,Colour.lilla,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Stockholm,Destination.Helsinki,4,Colour.valfri,false,2)); 
		ruteid++; routes.add(new Route (ruteid,Destination.Stockholm,Destination.Helsinki,4,Colour.gul,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Stockholm,Destination.Turku,3,Colour.blå,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Helsinki,Destination.Turku,1,Colour.kvit,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Helsinki,Destination.Tampere,1,Colour.oransje,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Helsinki,Destination.Lahti,1,Colour.svart,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Turku,Destination.Tampere,1,Colour.raud,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Tampere,Destination.Lahti,1,Colour.blå,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Helsinki,Destination.Imatra,3,Colour.raud,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Tampere,Destination.Vaasa,2,Colour.lilla,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Lahti,Destination.Imatra,2,Colour.gul,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Lahti,Destination.Kuopio,3,Colour.kvit,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Vaasa,Destination.Kuopio,4,Colour.valfri,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Imatra,Destination.Kuopio,2,Colour.lilla,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Kuopio,Destination.Lieksa,1,Colour.svart,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Kuopio,Destination.Kajaani,2,Colour.grønn,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Kuopio,Destination.Oulo,3,Colour.valfri,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Vaasa,Destination.Oulo,3,Colour.svart,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Kajaani,Destination.Oulo,2,Colour.gul,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Kajaani,Destination.Lieksa,1,Colour.blå,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Kuopio,Destination.Kajaani,2,Colour.grønn,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Lieksa,Destination.Murmansk,9,Colour.valfri,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Oulo,Destination.Tornio,1,Colour.kvit,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Oulo,Destination.Rovaniemi,2,Colour.oransje,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Tornio,Destination.Rovaniemi,1,Colour.raud,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Rovaniemi,Destination.Kirkenes,5,Colour.blå,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Tornio,Destination.Boden,1,Colour.grønn,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Boden,Destination.Kiruna,3,Colour.oransje,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Boden,Destination.Kiruna,3,Colour.svart,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Sundsvall,Destination.Umeå,3,Colour.lilla,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Sundsvall,Destination.Umeå,3,Colour.gul,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Sundsvall,Destination.Vaasa,3,Colour.blå,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Sundsvall,Destination.Ørebro,4,Colour.oransje,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Umeå,Destination.Boden,3,Colour.raud,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Umeå,Destination.Boden,3,Colour.kvit,false,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Umeå,Destination.Vaasa,1,Colour.valfri,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.MoIRana,Destination.Narvik,4,Colour.oransje,false,2));
		ruteid++; routes.add(new Route (ruteid,Destination.Narvik,Destination.Tromsø,3,Colour.gul,false,1));
		ruteid++; routes.add(new Route (ruteid,Destination.Kiruna,Destination.Narvik,1,Colour.lilla,true,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Kiruna,Destination.Narvik,1,Colour.kvit,true,0));
		ruteid++; routes.add(new Route (ruteid,Destination.Tromsø,Destination.Honningsvåg,4,Colour.lilla,false,2));
		ruteid++; routes.add(new Route (ruteid,Destination.Honningsvåg,Destination.Kirkenes,2,Colour.grønn,false,1));
		ruteid++; routes.add(new Route(ruteid,Destination.Kirkenes,Destination.Murmansk,3,Colour.kvit,false,1));
		return routes;
	}

	protected ArrayList<Mission> fyllMedOppdrag() {
		missions = new ArrayList<>();
		int oppdragsid = 0;
		missions.add(new Mission(oppdragsid,Destination.Oslo,Destination.MoIRana,10));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Bergen,Destination.København,9));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Narvik,Destination.Tallinn,13));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Helsinki,Destination.Lieksa,5));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Aalborg,Destination.Norrkøping,5));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Helsinki,Destination.København,10));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Helsinki,Destination.Bergen,12));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Helsinki,Destination.Østersund,8));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Bergen,Destination.Trondheim,7));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Ørebro,Destination.Kuopio,10));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stockholm,Destination.Bergen,8));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Turku,Destination.Trondheim,10));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stavanger,Destination.Karlskrona,8));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Oslo,Destination.Vaasa,9));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Oslo,Destination.Stavanger,4));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Sundsvall,Destination.Lahti,6));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Kristiansand,Destination.MoIRana,12));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stockholm,Destination.Kajaani,10));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Oslo,Destination.Stockholm,4));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Gøteborg,Destination.Oulo,12));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Helsinki,Destination.Kiruna,10));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Tornio,Destination.Imatra,6));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.København,Destination.Oulo,14));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Tampere,Destination.Tallinn,3));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Tromsø,Destination.Vaasa,11));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Narvik,Destination.Murmansk,12));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stockholm,Destination.Imatra,7));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Gøteborg,Destination.Turku,7));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Tampere,Destination.Boden,6));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Aalborg,Destination.Umeå,11));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Oslo,Destination.Helsinki,8));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Helsinki,Destination.Kirkenes,13));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Gøteborg,Destination.Åndalsnes,6));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stockholm,Destination.Umeå,7));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Århus,Destination.Lillehammer,6));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stockholm,Destination.København,6));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Norrkøping,Destination.Boden,11));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Tampere,Destination.Kristiansand,10));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Oslo,Destination.Honningsvåg,21));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Bergen,Destination.Tornio,17));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Bergen,Destination.Narvik,16));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stockholm,Destination.Tromsø,17));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.København,Destination.Murmansk,24));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.Stavanger,Destination.Rovaniemi,18));
		oppdragsid++;
		missions.add(new Mission(oppdragsid,Destination.København,Destination.Narvik,18));
		return missions;
	}
}